/*
  QUESTIONS CONFIG
  -----------------
  Generated by editor.html — edit here instead of by hand where possible.

  video     - filename of the clip, must live in the /videos folder
  answers   - exactly 4 answer strings
  correct   - index (0-3) of the correct answer in the answers array
*/

const QUESTIONS = [
  {
    video: "videos/Avo-Owl.webm",
    answers: ["Owl", "Avocado", "Egg", "Face"],
    correct: 0
  },
  {
    video: "videos/Boat.webm",
    answers: ["Boat", "Bird", "Castle", "Cheese"],
    correct: 0
  },
  {
    video: "videos/Camera-TV.webm",
    answers: ["TV", "Camera", "Box", "House"],
    correct: 0
  },
  {
    video: "videos/Cassette.webm",
    answers: ["Cassette", "VHS", "Envelope", "Horse"],
    correct: 0
  },
  {
    video: "videos/Castle.webm",
    answers: ["Castle", "Dollhouse", "Envelope", "Chess Piece"],
    correct: 0
  },
  {
    video: "videos/CD-Doughnut.webm",
    answers: ["Doughnut", "CD", "Egg", "Orange"],
    correct: 0
  },
  {
    video: "videos/Controller.webm",
    answers: ["Controller", "Car", "Lion", "Dolphin"],
    correct: 0
  },
  {
    video: "videos/Fish.webm",
    answers: ["Fish", "Chips", "Seal", "Necklace"],
    correct: 0
  },
  {
    video: "videos/Key.webm",
    answers: ["Key", "Flag", "Banana", "Lock"],
    correct: 0
  },
  {
    video: "videos/Ladder.webm",
    answers: ["Ladder", "Road", "Fire Engine", "Skis"],
    correct: 0
  },
  {
    video: "videos/Light-Balloon.webm",
    answers: ["Hot air balloon", "Light bulb", "Ball", "Clown"],
    correct: 0
  },
  {
    video: "videos/Mushroom.webm",
    answers: ["Mushroom", "Lamp", "Dragon", "Dinosaur"],
    correct: 0
  },
  {
    video: "videos/Robot.webm",
    answers: ["Robot", "Monster", "Helicopter", "Plane"],
    correct: 0
  },
  {
    video: "videos/Rocket.webm",
    answers: ["Rocket", "Lamp", "Fish Bowl", "Sushi"],
    correct: 0
  },
  {
    video: "videos/Snowman.webm",
    answers: ["Snowman", "Clown", "Knight", "Robot"],
    correct: 0
  },
  {
    video: "videos/Sock.webm",
    answers: ["Sock", "Shoe", "T Shirt", "Undies"],
    correct: 0
  }
];
